### ISSUE TITLE
Double Notifications

### ISSUE THREAD

**Issue by siveryt** [tomg404/pushnotifier-python#5]
Hey,
everytime I call the `pn.send_text` method in my python script, I'll get two notifications but I only get one print. Why is that?
here my code: (Devices censored)
```
print("Send Message!")
pn.send_text('Test!', silent=False, devices=['*****'])
```

**Comment by Tongvivi** [comment]
me too

**Comment by jakobmesserschmidt** [comment]
same

**Comment by 7omg** [comment]
Can't reproduce.
